### ISSUE TITLE
Refused to execute http://localhost:8080/main.js as script 에러

### ISSUE THREAD

**Issue by yujonglee** [CodeSoom/project-react-4-yujong-lee#34]
![이미지 2021  7  8  오후 7 12](https://user-images.githubusercontent.com/61503739/124904983-859a7680-e020-11eb-8547-027076bf72d2.jpg)

위 처럼 뜨면서 아무것도 렌더되지 않음.

`index.html`을 다음과 같이(type 추가) 수정해봤지만 해결되지 않음

```html
<html>
  <head>
    <link rel="stylesheet" type='text/css' href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type='text/css' href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <meta charset="UTF-8">
    <title>Tresk</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="text/javascript" src="/main.js"></script>
  </body>
</html>
```

**Comment by yujonglee** [comment]
분명히 이전에 동작했던 커밋으로 돌려서 해봐도 같은 문제가 발생해서 개발 환경의 문제인가 싶어 프로젝트를 삭제하고 다시 `clone`, `npm install` 해봤지만 동일합니다.

**Comment by Kihyun92** [comment]
어제 저녁에 받았던 코드에서는 잘 동작 하는데 이후에 어떤 작업이 있었을까요? 다시 돌려서 해보셨는데도 동일한게 이상하네요 🤔

브라우저 세팅 문제 일까요? 흠 저도 찾아봐야겠습니다

**Comment by yujonglee** [comment]
아직도 이런 동작이 완전히 이해되지는 않지만, #35 을 통해 해결되는 듯 합니다.
#33 때문에 어짜피 당장은 필요하지 않은 설정이라 제거해도 앱의 동작이 변하지 않습니다.
