### ISSUE TITLE
(form-onSubmit) VS (textField - onKeyDown)

### ISSUE THREAD

**Issue by yujonglee** [CodeSoom/project-react-4-yujong-lee#75]
현재 입력 필드에서 엔터로 추가하는 기능을  `onKeyDown`를 이용해 처리하고 있는데, 우연히 `form`으로 감싼 다음 여기에 `onSubmit`을 주는 방식을 어디서 보게 됨. 무엇이 더 나은 것인지 알아보고 생각해봐야 함.

**Comment by Kihyun92** [comment]
좋은 고민 같습니다 👍🏼  

인풋이 한개일때도 폼을 사용할때도 있지만, 저는 주로 여러개의 인풋과 한개의 등록 버튼이 있고,validation 등 처리를 해줘야할 때 form 을 사용했던 것 같아요 ㅎㅎ
