### ISSUE TITLE
PR 에 기존 커밋이 남아있는 이슈

### ISSUE THREAD

**Issue by moonkii** [CodeSoom/project-react-4-yujong-lee#9]
현재 Git 을 어떻게 사용하고 계신가요?
PR 마다 기존 커밋이 쌓여있어서 push 되고 있어요.
하나의 PR 에는 하나의 커밋만 남도록 해주세요.
만약 코드를 수정하거나 작업을 나눠서 한 경우에 커밋을 여러번 보낼 수 있는데 이경우에도 merge 직전에 커밋을 하나로 합쳐서 해주시면 돼요.

**Comment by yujonglee** [comment]
넵. 이전에 제가 `merge` 권한이 없었어서 계속 쌓여서 `PR`이 생성되었습니다.

#10 부터는 관련 커밋들만 모아 `squash`해서 올리고 있습니다!!
